### ISSUE TITLE
jshint warnings 

### ISSUE THREAD

**Issue by mpeters1** [interactive-pioneers/generator-pioneerapp#35]
components used: scss, assemble and modernizer

after build with components above grunt qa fails during jshint linter errors in grunfile.js and test/spec/test.js

**Comment by ain** [comment]
@mpeters1 you're welcome to send a PR. We should also write a spec against this failure:

- scaffold a new project
- see if jshint passes

**Comment by ain** [comment]
Fixed by #38.
