### ISSUE TITLE
Relative path bug

### ISSUE THREAD

**Issue by davleh** [interactive-pioneers/generator-pioneerapp#39]
Steps to reproduce:

1. Run generator with options: sass+assemble, including jquery, with tdd
2. Run grunt serve AND/OR
3. Run grunt build after fixing linter errors (see #38)

=> assets can not be found
=> folders de_DE, en_EN are generated into app folder instead of dist
=> buggy path generation /..scripts/ and /..styles

Expected: scripts, styles folders should be in dist (same with de_DE, en_EN?)

**Comment by ain** [comment]
Confirmed. It's an issue and it's what is commented. `assets` path is mismanaged as by task tag.

**Comment by ain** [comment]
Adding a slash would work as long as dev env is concerned, but it will fail for distribution. assemble/grunt-assemble#44 is still completely relevant here. Shouldn't have been closed.
